### ISSUE TITLE
peer-to-peer review 

### ISSUE THREAD

**Issue by Etsubdink-Demeke** [SnakyMz/Portfolio#3]
Great job so far :clap: 
only some change :recycle:  to make your project perfect 
- please change the heading or h1 font size so it matches the Figma design.
- please change the pixel measurements to relative measurements for responsiveness reasons.
Thanks  :grin:

**Comment by SnakyMz** [comment]
Thanks for the review. I have made changes as you specified and my page is much more responsive, well aligned and looks beautiful. This review has been very helpful.
